### ISSUE TITLE
host sweeps

### ISSUE THREAD

**Issue by gitthismoney** [reighnman/Graylog_Content_Pack_PaloAltoNetworks#11]
Hello,

Thank you so much for this, it's working great. 

Was wondering if there is any reason that host sweep threats are not indexed? Example of a single entry:

pa-hostname 1,2016/08/08 18:29:06,xxxxxxxxxxxx,THREAT,scan,1,2016/08/08 18:29:06,10.1.1.1,10.1.1.1,0.0.0.0,0.0.0.0,,,,not-applicable,vsys1,untrust,untrust,ethernet1/13,,logserver,2016/08/08 18:29:06,0,1,42296,25,0,0,0x0,tcp,drop,"",SCAN: Host Sweep(8002),any,medium,client-to-server,2006302,0x0,HU,CA,0,,0,,,0,,,,,,,,0,0,0,0,0,,pa-hostname,

there doesn't seem to be any grok filters for this type of threat. 

thanks!

**Comment by reighnman** [comment]
Thanks will check it out

**Comment by reighnman** [comment]
While I'd like to resolve this I no longer have access to Palo Alto firewalls (new company)  someone else will need to take this proj over.
