### ISSUE TITLE
7.x new fields

### ISSUE THREAD

**Issue by njdro** [reighnman/Graylog_Content_Pack_PaloAltoNetworks#6]
Can you implement the new fields? (Maybe there needs to be a 6.x and a 7.x branch?)

reference: https://www.paloaltonetworks.com/documentation/70/pan-os/pan-os/monitoring/syslog-field-descriptions

Thank you.

**Comment by reighnman** [comment]
It can probably be done in the same branch, will let you know :+1:

**Comment by daac87** [comment]
any updates on 7.x..

this is awesome stuff by the way!

**Comment by reighnman** [comment]
While I'd like to resolve this I no longer have access to Palo Alto firewalls (new company)

Someone else will have to take over the project sorry :(
